package modles
type AutoGenerated struct {
	Response struct {
		DataPoints []struct {
			Dimensions []struct {
				Value string `json:"Value"`
			} `json:"Dimensions"`
			Values []int `json:"Values"`
		} `json:"DataPoints"`
	} `json:"Response"`
}
